---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: bronco
  namespace: bronco
spec:
  baseDomain: cars2.lab
  clusterName: bronco
  pullSecretRef:
    name: assisted-deployment-pull-secret
  clusterImageSetNameRef: img4.20.14-x86-64-appsub
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  networkType: OVNKubernetes
  cpuPartitioningMode: AllNodes
  installConfigOverrides: '{"capabilities":{"baselineCapabilitySet": "None", "additionalEnabledCapabilities": [ "marketplace", "NodeTuning" ] }}'
  clusterLabels:
    common-du-416: "true"
    group-dellr760-vse4: ""
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    - cidr: fd01::/48
      hostPrefix: 64
  serviceNetwork:
    - cidr: 172.30.0.0/16
    - cidr: fd02::/112
  machineNetwork:
    - cidr: 192.168.38.128/26
    - cidr: 2600:52:7:300::0/64
  additionalNTPSources:
    - clock.cars2.lab
    - clock-v6.cars2.lab
  nodes:
    - hostName: spr760-1.bronco.cars2.lab
      role: master
      bmcAddress: "idrac-virtualmedia://192.168.38.208/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: bronco-bmc-creds-secret
      bootMACAddress: "ec:2a:72:51:31:b8"
      bootMode: UEFI
      rootDeviceHints:
        deviceName: "/dev/disk/by-path/pci-0000:c7:00.0-scsi-0:2:15:0"
      nodeNetwork:
        interfaces:
          - name: eno8303
            macAddress: "ec:2a:72:51:31:b8"
          - name: eno8403
            macAddress: "ec:2a:72:51:31:b9"
          - name: eno12399
            macAddress: "40:a6:b7:a8:79:c8"
          - name: eno12409
            macAddress: "40:a6:b7:a8:79:c9"
          - name: eno12419
            macAddress: "40:a6:b7:a8:79:ca"
          - name: eno12429
            macAddress: "40:a6:b7:a8:79:cb"
          - name: ens2f0
            macAddress: "50:7c:6f:1f:b3:98"
          - name: ens2f1
            macAddress: "50:7c:6f:1f:b3:99"
          - name: ens2f2
            macAddress: "50:7c:6f:1f:b3:9a"
          - name: ens2f3
            macAddress: "50:7c:6f:1f:b3:9b"
        config:
          interfaces:
            - name: eno8303
              type: ethernet
              state: up
              ipv4:
                enabled: true
                address:
                  - ip: "192.168.38.145"
                    prefix-length: 26
                dhcp: false
              ipv6:
                enabled: true
                address:
                  - ip: "2600:52:7:300::145"
                    prefix-length: 64
                autoconf: false
                dhcp: false
            - name: eno8403
              type: ethernet
              state: down
            - name: eno12399
              type: ethernet
              state: up
            - name: eno12409
              type: ethernet
              state: down
            - name: eno12419
              type: ethernet
              state: down
            - name: eno12429
              type: ethernet
              state: down
            - name: ens2f0
              type: ethernet
              state: down
            - name: ens2f1
              type: ethernet
              state: down
            - name: ens2f2
              type: ethernet
              state: down
            - name: ens2f3
              type: ethernet
              state: down
          dns-resolver:
            config:
              search:
                - cars2.lab
              server:
                - 192.168.38.12
                - 2600:52:7:38::12
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.38.129
                next-hop-interface: eno8303
              - destination: ::/0
                next-hop-address: 2600:52:7:300::1
                next-hop-interface: eno8303
