---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cars2-day2-policies
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ztp-policies
  project: default
  source:
    path: 02-day2-policies
    repoURL: https://github.com/apj72/bronco-sno
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
