---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - placement.yaml
  - policy-cluster-tuning.yaml
  - policy-catalog-source.yaml
  - policy-operator-subs.yaml
  - policy-sriov-config.yaml
  - policy-ptp-config.yaml
  - policy-performance.yaml
  - policy-sctp.yaml
  - policy-disable-console.yaml
  - cgu-bronco-day2.yaml
