---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: common-du-cluster-tuning
  namespace: bronco
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Telco RAN DU RDS
    ran.openshift.io/ztp-deploy-wave: "1"
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-monitoring-config
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-monitoring-config
                  namespace: openshift-monitoring
                data:
                  config.yaml: |
                    alertmanagerMain:
                      enabled: false
                    telemeterClient:
                      enabled: false
                    prometheusK8s:
                      retention: 24h
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: console-operator-disable
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  logLevel: Normal
                  managementState: Removed
                  operatorLogLevel: Normal
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: network-diagnostics-disable
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Network
                metadata:
                  name: cluster
                spec:
                  disableNetworkDiagnostics: true
