---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: common-du-disable-console
  namespace: ztp-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Telco RAN DU RDS
    ran.openshift.io/ztp-deploy-wave: "1"
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: disable-console-operator
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  managementState: Removed
