---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: common-du-catalog-source
  namespace: ztp-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Telco RAN DU RDS
    ran.openshift.io/ztp-deploy-wave: "1"
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: catalog-source
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: redhat-operators
                  namespace: openshift-marketplace
                spec:
                  displayName: Red Hat Operators
                  image: registry.redhat.io/redhat/redhat-operator-index:v4.20
                  publisher: Red Hat
                  sourceType: grpc
                  grpcPodConfig:
                    securityContextConfig: restricted
                  updateStrategy:
                    registryPoll:
                      interval: 10m
